debug: false
server:
  port: 9007

spring:
  application:
    name: eureka-server
  profiles:
    active: dev


eureka:
  instance:
    hostname: 127.0.0.1
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:9007/eureka/


management:
  endpoint:
    health:
      show-details: ALWAYS




